version: 2

run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - golang.org/x/example
          - golang.org/x/example/hello
          - golang.org/x/example/hello/reverse
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
issues:
  exclude-rules:
    - path: (^|/)main\.go$
      linters:
        - depguard
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
